Add paper converter
hyperskill/hyperstyle-analyze pull request #29
Opened 2022-07-19 19:33 UTC by nbirillo

Add a base converter for the algorithm for detections issues in templates

2022-07-20 15:16 UTC, tiginamaria requested changes
Greate! Thank you! Fills like you are very tired =( Probably I can fix all comments if you want, because they are only about style, not idea. Also, I think I should go into details of all of this module and write some tests before giving it for industrial usage?

2022-07-20 15:16 UTC, tiginamaria commented on analysis/src/python/data_analysis/template_errors/postprocessing.py
> +    lowest_threshold = 0.1
Maybe to set by console parameters with default values?

2022-07-20 15:16 UTC, tiginamaria commented on analysis/src/python/data_analysis/template_errors/postprocessing.py
> +        lambda row: f'https://hyperskill.org/learn/step/{row[SubmissionColumns.STEP_ID.value]}', axis=1)
Maybe somehow get from dataset with steps of unify with [`analysis/src/python/data_collection/hyperskill/api/steps.py`](https://github.com/hyperskill/hyperstyle-analyze/blob/21db5d9d14e8e83d946f2d81c8249c6561d005ea/analysis/src/python/data_collection/hyperskill/api/steps.py#L103)

2022-07-20 15:16 UTC, tiginamaria commented on analysis/src/python/data_analysis/template_errors/postprocessing.py
> +    template_issues_df['task_link'] = template_issues_df.apply(
There is already name for such column `analysis.src.python.data_analysis.model.column_name.StepColumns.URL`

2022-07-20 15:16 UTC, tiginamaria commented on analysis/src/python/data_analysis/template_errors/postprocessing.py
> +    write_df(template_issues, f'{base_path}/template_issues.csv')
Maybe usage of `Path` and `AnalysisExtension.CSV` will make this code better

2022-07-21 06:51 UTC, nbirillo commented
I will fix it today and add tests, thank you! But first, I need to complete the analytics part for the paper...

2022-07-21 14:46 UTC, tiginamaria approved these changes
Looks perfect! Thanks!

2022-07-22 10:34 UTC, merged