Add tests for parsing hyperstyle results
hyperskill/hyperstyle-analyze pull request #32
Opened 2022-07-27 10:10 UTC by tiginamaria

Add test for parsing hyperstyle and qodana reports

2022-08-01 13:46 UTC, nbirillo requested changes
Great!

2022-08-01 13:46 UTC, nbirillo commented on analysis/test/python/evaluation/qodana/test_parse_result.py
> +        assert len(report.list_problem) == issues_count[i]
What do you think?

2022-08-02 07:58 UTC, tiginamaria commented on analysis/test/python/evaluation/qodana/test_parse_result.py
> +        assert len(report.list_problem) == issues_count[i]
Add special methods for common tests running and config generation.

2022-08-02 13:35 UTC, nbirillo approved these changes
Great, thank you!

2022-08-02 13:35 UTC, merged