Benchmark
hyperskill/hyperstyle-analyze pull request #34
Opened 2022-07-29 10:03 UTC by GirZ0n

2022-08-02 13:58 UTC, nbirillo requested changes
Great! I have several small comments

2022-08-02 13:58 UTC, nbirillo commented on analysis/src/python/data_analysis/statistics/submissions_metrics_statistics.py
> +    code_lines_count: Optional[Literal['all', 'ignore_empty_lines']] = None,
please, add an enum or something like this for 'all', 'ignore_empty_lines'

2022-08-02 13:58 UTC, nbirillo commented on analysis/src/python/evaluation/benchmark/benchmark.py
> +    for i in range(1, repeat + 1):
range(repeat)? and logger.info(f'Time measuring attempt={i + 1}')?

2022-08-02 13:58 UTC, nbirillo commented on analysis/src/python/evaluation/benchmark/benchmark.py
> +    mean_time = measure_run_time(
probably it is better to add a cli argument to choose what time to check the user wants: mean or median. What do you think?

2022-08-03 16:41 UTC, nbirillo requested changes
One more comment

2022-08-03 16:41 UTC, nbirillo commented on analysis/src/python/evaluation/benchmark/benchmark.py
> +class AggregateOption(Enum):
Can we unify this class with [this](https://github.com/hyperskill/hyperstyle-analyze/blob/main/analysis/src/python/data_analysis/template_errors/models/postprocessing_models.py#L10) class?

2022-08-07 12:02 UTC, nbirillo commented
@GirZ0n can I check it?

2022-08-08 06:11 UTC, GirZ0n commented
@nbirillo, yes, you can. I forgot to re-request a review :sweat_smile:

2022-08-08 07:22 UTC, nbirillo approved these changes
Perfect! Thank you!

2022-08-08 07:22 UTC, merged